CREATE TABLE `checkout_settlements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `settlement_no` VARCHAR(40) NOT NULL, `contract_id` INT UNSIGNED NOT NULL,
  `checkout_type` VARCHAR(50) NOT NULL, `planned_checkout_date` DATE NOT NULL, `actual_checkout_date` DATE NULL, `handover_date` DATE NULL, `inspection_at` DATETIME(3) NULL, `checkout_reason` VARCHAR(500) NOT NULL,
  `rent_receivable` DECIMAL(14,2) NOT NULL DEFAULT 0, `rent_received` DECIMAL(14,2) NOT NULL DEFAULT 0, `rent_outstanding` DECIMAL(14,2) NOT NULL DEFAULT 0, `prepayment_balance` DECIMAL(14,2) NOT NULL DEFAULT 0, `deposit_balance` DECIMAL(14,2) NOT NULL DEFAULT 0, `deposit_offset_amount` DECIMAL(14,2) NOT NULL DEFAULT 0, `other_deduction_amount` DECIMAL(14,2) NOT NULL DEFAULT 0, `deposit_refundable_amount` DECIMAL(14,2) NOT NULL DEFAULT 0, `prepayment_refundable_amount` DECIMAL(14,2) NOT NULL DEFAULT 0, `final_receivable` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `target_room_status` ENUM('EMPTY','PENDING_MOVE_IN','RENTED','PENDING_CHECKOUT','MAINTENANCE','FOR_SALE','SOLD','DISABLED','OTHER') NOT NULL,
  `status` ENUM('DRAFT','PENDING','APPROVED','REJECTED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'DRAFT', `submitted_by` INT UNSIGNED NOT NULL, `submitted_at` DATETIME(3) NULL, `approved_by` INT UNSIGNED NULL, `approved_at` DATETIME(3) NULL, `rejected_reason` VARCHAR(500) NULL, `remark` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_checkout_settlement_no` (`settlement_no`), KEY `idx_checkout_contract_status` (`contract_id`,`status`), CONSTRAINT `fk_checkout_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `deposit_refunds` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `refund_no` VARCHAR(40) NOT NULL, `contract_id` INT UNSIGNED NOT NULL, `checkout_settlement_id` INT UNSIGNED NOT NULL, `refund_amount` DECIMAL(14,2) NOT NULL, `refund_date` DATE NOT NULL,
  `refund_method` ENUM('WECHAT','ALIPAY','BANK_TRANSFER','CASH','POS','OTHER') NOT NULL, `remark` VARCHAR(1000) NULL, `approval_status` ENUM('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING', `submitted_by` INT UNSIGNED NOT NULL, `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `approved_by` INT UNSIGNED NULL, `approved_at` DATETIME(3) NULL, `cancelled_reason` VARCHAR(500) NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uq_deposit_refund_no` (`refund_no`), KEY `idx_deposit_refund_contract` (`contract_id`,`approval_status`), KEY `idx_deposit_refund_settlement` (`checkout_settlement_id`,`approval_status`), CONSTRAINT `fk_deposit_refund_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`), CONSTRAINT `fk_deposit_refund_settlement` FOREIGN KEY (`checkout_settlement_id`) REFERENCES `checkout_settlements`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `deposit_transactions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `contract_id` INT UNSIGNED NOT NULL, `transaction_no` VARCHAR(40) NOT NULL, `transaction_type` ENUM('RECEIPT','OFFSET_ARREARS','OFFSET_SETTLEMENT','REFUND','REVERSAL','ADJUSTMENT') NOT NULL, `amount` DECIMAL(14,2) NOT NULL, `balance_after` DECIMAL(14,2) NOT NULL, `payment_id` INT UNSIGNED NULL, `rent_bill_id` INT UNSIGNED NULL, `checkout_settlement_id` INT UNSIGNED NULL, `deposit_refund_id` INT UNSIGNED NULL, `reason` VARCHAR(500) NULL, `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE KEY `uq_deposit_transaction_no` (`transaction_no`), KEY `idx_deposit_contract_date` (`contract_id`,`occurred_at`), KEY `idx_deposit_payment` (`payment_id`), KEY `idx_deposit_bill` (`rent_bill_id`), KEY `idx_deposit_settlement` (`checkout_settlement_id`), KEY `idx_deposit_refund` (`deposit_refund_id`), CONSTRAINT `fk_deposit_contract` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`), CONSTRAINT `fk_deposit_payment` FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`), CONSTRAINT `fk_deposit_bill` FOREIGN KEY (`rent_bill_id`) REFERENCES `rent_bills`(`id`), CONSTRAINT `fk_deposit_settlement` FOREIGN KEY (`checkout_settlement_id`) REFERENCES `checkout_settlements`(`id`), CONSTRAINT `fk_deposit_refund` FOREIGN KEY (`deposit_refund_id`) REFERENCES `deposit_refunds`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `checkout_settlement_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `checkout_settlement_id` INT UNSIGNED NOT NULL, `item_type` ENUM('RENT_ARREARS','DAMAGE','REPAIR','CLEANING','OTHER') NOT NULL, `amount` DECIMAL(14,2) NOT NULL, `rent_bill_id` INT UNSIGNED NULL, `inspection_record_ref` VARCHAR(100) NULL, `description` VARCHAR(500) NOT NULL, `evidence_required` BOOLEAN NOT NULL DEFAULT FALSE, `confirmed_by_tenant` BOOLEAN NOT NULL DEFAULT FALSE, `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`), KEY `idx_checkout_item_settlement` (`checkout_settlement_id`,`sort_order`), KEY `idx_checkout_item_bill` (`rent_bill_id`), CONSTRAINT `fk_checkout_item_settlement` FOREIGN KEY (`checkout_settlement_id`) REFERENCES `checkout_settlements`(`id`), CONSTRAINT `fk_checkout_item_bill` FOREIGN KEY (`rent_bill_id`) REFERENCES `rent_bills`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `deposit_refund_files` (`deposit_refund_id` INT UNSIGNED NOT NULL, `file_asset_id` INT UNSIGNED NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`deposit_refund_id`,`file_asset_id`), CONSTRAINT `fk_deposit_refund_file_refund` FOREIGN KEY (`deposit_refund_id`) REFERENCES `deposit_refunds`(`id`), CONSTRAINT `fk_deposit_refund_file_asset` FOREIGN KEY (`file_asset_id`) REFERENCES `file_assets`(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `checkout_settlement_item_files` (`checkout_settlement_item_id` INT UNSIGNED NOT NULL, `file_asset_id` INT UNSIGNED NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`checkout_settlement_item_id`,`file_asset_id`), CONSTRAINT `fk_checkout_item_file_item` FOREIGN KEY (`checkout_settlement_item_id`) REFERENCES `checkout_settlement_items`(`id`), CONSTRAINT `fk_checkout_item_file_asset` FOREIGN KEY (`file_asset_id`) REFERENCES `file_assets`(`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
