<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PaymentWorkspace from '../../components/payments/PaymentWorkspace.vue'
import { paymentApi } from '../../services/payments'
import { useSessionStore } from '../../stores/session'
import type { ReviewItem } from '../../types/payments'
import { refundAdjustmentDecisions } from './payment-review'

const session = useSessionStore(); const queue = ref<ReviewItem[]>([]); const selected = ref<ReviewItem|null>(null); const detail = ref<Record<string,any>|null>(null); const loading=ref(false); const acting=ref(false)
const filters=reactive({type:'',status:'PENDING',roomKeyword:'',tenantKeyword:'',dateFrom:'',dateTo:''})
const decisions=reactive<Record<number,{decision:'REVERSE'|'KEEP';keepReason:string}>>({})
const isSuperAdmin=computed(()=>session.user?.role==='SUPER_ADMIN')
const statusText:Record<string,string>={PENDING:'待确认',APPROVED:'已确认',REJECTED:'已驳回',CANCELLED:'已取消'}
function money(value:unknown){return value===null||value===undefined?'—':`¥${Number(value).toFixed(2)}`}
function date(value:unknown){return value?String(value).slice(0,10):'—'}
async function load(){loading.value=true;try{queue.value=await paymentApi.reviews(Object.fromEntries(Object.entries(filters).filter(([,value])=>value)));if(selected.value){const latest=queue.value.find((item)=>item.type===selected.value?.type&&item.id===selected.value?.id);if(!latest){selected.value=null;detail.value=null}}}finally{loading.value=false}}
async function choose(item:ReviewItem){selected.value=item;detail.value=await paymentApi.reviewDetail(item.type,item.id);Object.keys(decisions).forEach((key)=>delete decisions[Number(key)]);if(item.type==='REFUND')Object.assign(decisions,refundAdjustmentDecisions(detail.value))}
async function approve(){if(!selected.value)return;const adjustmentDecisions=Object.entries(decisions).map(([id,item])=>({billAdjustmentId:Number(id),decision:item.decision,keepReason:item.decision==='KEEP'?item.keepReason:undefined}));if(adjustmentDecisions.some((item)=>item.decision==='KEEP'&&!item.keepReason?.trim()))return ElMessage.warning('保留优惠时必须填写原因');acting.value=true;try{await paymentApi.approveReview(selected.value.type,selected.value.id,adjustmentDecisions);ElMessage.success('审核已确认，账务冲回已完成');selected.value=null;detail.value=null;await load()}finally{acting.value=false}}
async function reject(){if(!selected.value)return;const reason=await ElMessageBox.prompt('请输入驳回原因','驳回申请',{inputPattern:/\S+/,inputErrorMessage:'驳回原因不能为空'}).then((result)=>result.value);acting.value=true;try{await paymentApi.rejectReview(selected.value.type,selected.value.id,reason);ElMessage.success('申请已驳回');selected.value=null;detail.value=null;await load()}finally{acting.value=false}}
onMounted(()=>void load())
</script>

<template>
  <PaymentWorkspace title="退款/作废确认" description="待确认事项优先显示；确认后系统自动冲回账单、预收款及相关优惠。">
    <el-alert v-if="!isSuperAdmin" title="您可以查看审核进度；只有超级管理员可以确认或驳回。" type="info" :closable="false" show-icon/>
    <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="类型"><el-select v-model="filters.type" clearable placeholder="全部" style="width:130px"><el-option label="退款" value="REFUND"/><el-option label="作废" value="VOID"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="filters.status" clearable placeholder="全部" style="width:130px"><el-option v-for="(label,value) in statusText" :key="value" :label="label" :value="value"/></el-select></el-form-item><el-form-item label="房号"><el-input v-model="filters.roomKeyword" clearable/></el-form-item><el-form-item label="租户"><el-input v-model="filters.tenantKeyword" clearable/></el-form-item><el-form-item label="申请日期"><el-date-picker v-model="filters.dateFrom" type="date" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" placeholder="开始日期"/></el-form-item><el-form-item><el-date-picker v-model="filters.dateTo" type="date" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" placeholder="结束日期"/></el-form-item><el-button type="primary" @click="load">查询</el-button></el-form></el-card>
    <div class="review-layout" v-loading="loading">
      <el-card shadow="never" class="queue"><template #header><div class="queue-title"><b>审核队列</b><el-badge :value="queue.filter(item=>item.status==='PENDING').length" type="danger"/></div></template><button v-for="item in queue" :key="`${item.type}-${item.id}`" class="queue-item" :class="{active:selected?.type===item.type&&selected?.id===item.id}" @click="choose(item)"><span><el-tag size="small" :type="item.type==='REFUND'?'warning':'danger'">{{item.type==='REFUND'?'退款':'作废'}}</el-tag><b>{{item.requestNo}}</b><small>{{item.contract.room?.fullHouseNo}} · {{item.tenant?.name??'未登记租户'}}</small></span><span><b>{{money(item.amount)}}</b><small>{{date(item.submittedAt)}}</small><em :class="item.status.toLowerCase()">{{statusText[item.status]??item.status}}</em></span></button><el-empty v-if="!queue.length" description="当前没有待处理事项"/></el-card>
      <div v-if="detail&&selected" class="review-detail">
        <el-card shadow="never"><div class="review-head"><div><el-tag :type="selected.type==='REFUND'?'warning':'danger'">{{selected.type==='REFUND'?'退款申请':'作废申请'}}</el-tag><h2>{{selected.requestNo}}</h2><p>关联票据 {{selected.receiptNo}} · {{selected.contract.contractNo}}</p></div><div class="review-amount"><small>{{selected.type==='REFUND'?'申请退款金额':'原收款金额'}}</small><b>{{money(selected.type==='REFUND'?detail.refundAmount:detail.payment?.amount)}}</b></div></div><el-descriptions :column="2" border class="description"><el-descriptions-item label="房号">{{selected.contract.room?.fullHouseNo}}</el-descriptions-item><el-descriptions-item label="租户">{{selected.tenant?.name??'—'}} {{selected.tenant?.phone??''}}</el-descriptions-item><el-descriptions-item label="申请日期">{{date(detail.submittedAt)}}</el-descriptions-item><el-descriptions-item label="状态">{{statusText[detail.approvalStatus]??detail.approvalStatus}}</el-descriptions-item><el-descriptions-item label="申请原因" :span="2">{{detail.reason}}</el-descriptions-item></el-descriptions></el-card>
        <el-card v-if="selected.type==='REFUND'" shadow="never"><template #header><b>退款分配明细</b></template><el-table :data="detail.allocations??[]" size="small"><el-table-column label="账期"><template #default="{row}">第 {{row.paymentAllocation?.rentBill?.periodSeq}} 期</template></el-table-column><el-table-column label="账单编号" prop="paymentAllocation.rentBill.billNo"/><el-table-column label="本次冲回" align="right"><template #default="{row}">{{money(row.reversedAmount)}}</template></el-table-column></el-table></el-card>
        <el-card v-if="selected.type==='REFUND'&&Object.keys(decisions).length>0" shadow="never"><template #header><div><b>关联优惠处理</b><p class="card-tip">默认随退款冲回；如业务上需保留，必须逐项说明原因。</p></div></template><div v-for="item in detail.payment.adjustments.filter((row:any)=>decisions[row.id])" :key="item.id" class="decision-row"><div><b>{{item.adjustmentNo}} · {{item.adjustmentType}}</b><small>{{money(item.amount)}} · {{item.reason}}</small></div><el-radio-group v-model="decisions[item.id].decision"><el-radio-button value="REVERSE">随退款冲回</el-radio-button><el-radio-button value="KEEP">保留优惠</el-radio-button></el-radio-group><el-input v-if="decisions[item.id].decision==='KEEP'" v-model="decisions[item.id].keepReason" placeholder="请输入保留原因（必填）"/></div></el-card>
        <el-card v-if="selected.type==='VOID'" shadow="never"><template #header><b>作废影响预览</b></template><div class="impact-grid"><div><small>账期分配</small><b>{{detail.payment?.allocations?.length??0}} 条将冲回</b></div><div><small>预收款流水</small><b>{{detail.payment?.prepaymentTransactions?.length??0}} 条将冲回</b></div><div><small>关联优惠</small><b>{{detail.payment?.adjustments?.length??0}} 条将处理</b></div></div><el-alert title="原收款记录、票据和审批痕迹不会删除，将标记为已作废。" type="error" :closable="false"/></el-card>
        <div v-if="selected.status==='PENDING'&&isSuperAdmin" class="review-actions"><el-button size="large" @click="reject">驳回申请</el-button><el-button type="primary" size="large" :loading="acting" @click="approve">确认并执行账务冲回</el-button></div>
      </div><el-empty v-else class="empty-detail" description="从左侧选择一项查看完整申请"/>
    </div>
  </PaymentWorkspace>
</template>

<style scoped>
.filter-card :deep(.el-form-item){margin-bottom:0}.review-layout{display:grid;grid-template-columns:330px minmax(0,1fr);gap:16px;align-items:start}.queue{position:sticky;top:88px}.queue :deep(.el-card__body){padding:0}.queue-title{display:flex;justify-content:space-between}.queue-item{display:flex;width:100%;justify-content:space-between;gap:10px;padding:15px;border:0;border-bottom:1px solid #edf0f4;background:#fff;color:#344258;text-align:left;cursor:pointer}.queue-item:hover,.queue-item.active{background:#edf4ff}.queue-item span{display:grid;justify-items:start;gap:6px}.queue-item span:last-child{justify-items:end}.queue-item small{color:#8996a8}.queue-item em{font-size:12px;font-style:normal}.queue-item em.pending{color:#e68622}.queue-item em.approved{color:#2e9c62}.queue-item em.rejected{color:#d75555}.review-detail{display:grid;gap:16px}.review-head{display:flex;justify-content:space-between}.review-head h2{margin:10px 0 5px}.review-head p,.card-tip{margin:0;color:#8190a4;font-size:13px}.review-amount{display:grid;align-content:center;justify-items:end;gap:7px}.review-amount small{color:#7d8a9d}.review-amount b{color:#e16a36;font-size:25px}.description{margin-top:20px}.decision-row{display:grid;grid-template-columns:minmax(180px,1fr) auto minmax(190px,1fr);gap:14px;align-items:center;padding:14px 0;border-bottom:1px solid #edf0f5}.decision-row>div{display:grid;gap:5px}.decision-row small{color:#8190a4}.impact-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}.impact-grid div{display:grid;gap:8px;padding:16px;border-radius:9px;background:#f5f7fb}.impact-grid small{color:#7f8da0}.review-actions{display:flex;justify-content:flex-end;padding:16px;border:1px solid #dfe6f0;border-radius:10px;background:#fff}.empty-detail{padding:80px;background:#fff;border-radius:10px}@media(max-width:1100px){.review-layout{grid-template-columns:1fr}.queue{position:static}.decision-row{grid-template-columns:1fr}}@media(max-width:700px){.impact-grid{grid-template-columns:1fr}}
</style>
