<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import PaymentWorkspace from '../../components/payments/PaymentWorkspace.vue'
import { paymentApi } from '../../services/payments'
import { useSessionStore } from '../../stores/session'
import type { PaymentDetail, PaymentListItem, PaymentMethod } from '../../types/payments'
import { refundableAllocationTotal } from './payment-review'
import { paymentLifecycleTags } from './payment-lifecycle-tags'
import { approvalStatusLabel, billAdjustmentTypeLabel } from '../../utils/status-labels'

const route = useRoute(); const router = useRouter(); const session = useSessionStore()
const rows = ref<PaymentListItem[]>([]); const detail = ref<PaymentDetail | null>(null); const loading = ref(false)
const filters = reactive({ receiptNo: '', roomKeyword: '', tenantKeyword: '', dateFrom: '', dateTo: '' })
const refundOpen = ref(false); const voidOpen = ref(false); const editOpen = ref(false)
const refund = reactive({ refundAmount: '', refundDate: new Date().toISOString().slice(0,10), refundMethod: 'BANK_TRANSFER' as PaymentMethod, reason: '', allocations: {} as Record<number,string> })
const edit = reactive({ paymentDate: '', amount: '', method: 'WECHAT' as PaymentMethod, externalReference: '', remark: '', editReason: '' })
const voidReason = ref('')
const isAdmin = computed(() => ['SUPER_ADMIN','ADMIN'].includes(session.user?.role ?? ''))
const isSuperAdmin = computed(() => session.user?.role === 'SUPER_ADMIN')
const lifecycleTags = computed(() => detail.value ? paymentLifecycleTags(detail.value) : [])
const methodText: Record<string,string> = { WECHAT:'微信', ALIPAY:'支付宝', BANK_TRANSFER:'银行转账', CASH:'现金', POS:'POS', OTHER:'其他' }
function money(value: unknown) { return `¥${Number(value ?? 0).toFixed(2)}` }
function date(value: unknown) { return value ? String(value).slice(0,10) : '—' }
function printReceipt() { window.print() }

async function search() {
  loading.value = true
  try { rows.value = await paymentApi.list(Object.fromEntries(Object.entries(filters).filter(([,value]) => value))) } finally { loading.value = false }
}
async function openDetail(id: number) {
  loading.value = true
  try { detail.value = await paymentApi.detail(id); if (Number(route.params.id) !== id) await router.replace(`/payments/detail/${id}`) } finally { loading.value = false }
}
async function initialize() { await search(); const id = Number(route.params.id); if (id > 0) await openDetail(id); else if (rows.value[0]) await openDetail(rows.value[0].id) }
async function download(file: PaymentDetail['files'][number]) {
  if (!detail.value) return
  const response = await paymentApi.downloadProof(detail.value.id, file.id); const url = URL.createObjectURL(response.data)
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.originalName; anchor.click(); URL.revokeObjectURL(url)
}
function prepareRefund() { if (!detail.value) return; const active=detail.value.allocations.filter((item)=>Number(item.effectiveAmount)>0); refund.refundAmount=refundableAllocationTotal(active); refund.reason=''; refund.allocations=Object.fromEntries(active.map((item)=>[item.id,item.effectiveAmount])); refundOpen.value=true }
async function submitRefund() {
  if (!detail.value || Number(refund.refundAmount)<=0 || !refund.reason.trim()) return ElMessage.warning('请填写退款金额和原因')
  await paymentApi.submitRefund({ paymentId:detail.value.id, refundAmount:refund.refundAmount, refundDate:refund.refundDate, refundMethod:refund.refundMethod, reason:refund.reason, allocations:Object.entries(refund.allocations).filter(([,amount])=>Number(amount)>0).map(([id,amount])=>({paymentAllocationId:Number(id),amount})) })
  refundOpen.value=false; ElMessage.success('退款申请已提交，等待超级管理员确认'); await openDetail(detail.value.id)
}
async function submitVoid() { if (!detail.value || !voidReason.value.trim()) return ElMessage.warning('请填写作废原因'); await paymentApi.submitVoid({paymentId:detail.value.id,reason:voidReason.value}); voidOpen.value=false; ElMessage.success('作废申请已提交'); await openDetail(detail.value.id) }
function prepareEdit() { if (!detail.value) return; Object.assign(edit,{paymentDate:date(detail.value.paymentDate),amount:detail.value.amount,method:detail.value.method,externalReference:detail.value.externalReference??'',remark:detail.value.remark??'',editReason:''}); editOpen.value=true }
async function submitEdit() { if (!detail.value || !edit.editReason.trim()) return ElMessage.warning('请填写修改原因'); await paymentApi.edit(detail.value.id,{...edit,externalReference:edit.externalReference||null,remark:edit.remark||null}); editOpen.value=false; ElMessage.success('收款信息已更正并记录审计日志'); await openDetail(detail.value.id) }
async function decideAdjustment(id:number, approve:boolean) { let reason=''; if(!approve) reason=await ElMessageBox.prompt('请输入驳回原因','驳回优惠/减免').then((result)=>result.value); if(approve) await paymentApi.approveAdjustment(id); else await paymentApi.rejectAdjustment(id,reason); ElMessage.success(approve?'已确认':'已驳回'); if(detail.value) await openDetail(detail.value.id) }
onMounted(() => void initialize())
</script>

<template>
  <PaymentWorkspace title="收款详情" description="按票据、房号、租户或日期查询，查看每一笔收款的完整资金轨迹。">
    <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="票据号"><el-input v-model="filters.receiptNo" clearable /></el-form-item><el-form-item label="房号"><el-input v-model="filters.roomKeyword" clearable /></el-form-item><el-form-item label="租户"><el-input v-model="filters.tenantKeyword" clearable /></el-form-item><el-form-item label="日期"><el-date-picker v-model="filters.dateFrom" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" type="date" placeholder="开始日期" /></el-form-item><el-form-item><el-date-picker v-model="filters.dateTo" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" type="date" placeholder="结束日期" /></el-form-item><el-button type="primary" @click="search">查询</el-button></el-form></el-card>
    <div class="detail-layout" v-loading="loading">
      <el-card shadow="never" class="record-list"><template #header><b>收款记录（{{ rows.length }}）</b></template><button v-for="row in rows" :key="row.id" class="record-item" :class="{active:detail?.id===row.id}" @click="openDetail(row.id)"><span><b>{{ row.receiptNo }}</b><small>{{ row.contract.room?.fullHouseNo }} · {{ row.tenant?.name ?? '未登记租户' }}</small></span><span><b>{{ money(row.amount) }}</b><small>{{ date(row.paymentDate) }}</small></span></button><el-empty v-if="!rows.length" description="没有匹配的收款记录" /></el-card>
      <div v-if="detail" class="detail-content">
        <el-card shadow="never"><div class="receipt-head"><div><div class="receipt-tags"><el-tag v-for="tag in lifecycleTags" :key="tag.text" :type="tag.type">{{ tag.text }}</el-tag></div><h2>{{ detail.receiptNo }}</h2><p>{{ detail.contract.contractNo }} · {{ detail.contract.room?.fullHouseNo }} · {{ detail.tenant?.name ?? '未登记租户' }}</p></div><div class="actions"><el-button @click="printReceipt">打印票据</el-button><el-button v-if="isSuperAdmin" @click="prepareEdit">更正</el-button><el-button v-if="isAdmin" @click="prepareRefund">申请退款</el-button><el-button v-if="isAdmin" type="danger" plain @click="voidOpen=true">申请作废</el-button></div></div><div class="metrics"><div><small>本次实收</small><b>{{ money(detail.metrics.receivedAmount) }}</b></div><div><small>已确认优惠</small><b>{{ money(detail.metrics.confirmedAdjustmentAmount) }}</b></div><div><small>转入预收款</small><b>{{ money(detail.metrics.prepaymentAmount) }}</b></div><div><small>覆盖账期</small><b>{{ detail.metrics.coveredBillCount }} 期</b></div></div></el-card>
        <el-card shadow="never"><template #header><b>账期分配</b></template><el-table :data="detail.allocations" size="small"><el-table-column prop="allocationOrder" label="顺序" width="65"/><el-table-column label="账期"><template #default="{row}">第 {{ row.bill.periodSeq }} 期</template></el-table-column><el-table-column label="区间" min-width="180"><template #default="{row}">{{date(row.bill.periodStart)}} 至 {{date(row.bill.periodEnd)}}</template></el-table-column><el-table-column label="分配金额" align="right"><template #default="{row}">{{money(row.allocatedAmount)}}</template></el-table-column><el-table-column label="已冲回" align="right"><template #default="{row}">{{money(row.reversedAmount)}}</template></el-table-column><el-table-column label="有效金额" align="right"><template #default="{row}"><b>{{money(row.effectiveAmount)}}</b></template></el-table-column></el-table></el-card>
        <el-card shadow="never"><template #header><b>优惠与减免</b></template><el-table :data="detail.adjustments" size="small"><el-table-column prop="adjustmentNo" label="编号"/><el-table-column label="类型"><template #default="{ row }">{{ billAdjustmentTypeLabel(row.adjustmentType) }}</template></el-table-column><el-table-column label="金额"><template #default="{row}">{{money(row.amount)}}</template></el-table-column><el-table-column prop="reason" label="原因"/><el-table-column label="状态"><template #default="{row}"><el-tag>{{approvalStatusLabel(row.approvalStatus)}}</el-tag></template></el-table-column><el-table-column v-if="isSuperAdmin" label="确认"><template #default="{row}"><template v-if="row.approvalStatus==='PENDING'"><el-button link type="primary" @click="decideAdjustment(row.id,true)">确认</el-button><el-button link type="danger" @click="decideAdjustment(row.id,false)">驳回</el-button></template></template></el-table-column></el-table><el-empty v-if="!detail.adjustments.length" description="无优惠或减免" /></el-card>
        <div class="detail-columns"><el-card shadow="never"><template #header><b>收款凭证</b></template><div v-for="file in detail.files" :key="file.id" class="file-row"><span>{{file.originalName}}</span><el-button link type="primary" @click="download(file)">下载</el-button></div><el-empty v-if="!detail.files.length" description="未上传凭证" /></el-card><el-card shadow="never"><template #header><b>基础信息</b></template><el-descriptions :column="1"><el-descriptions-item label="收款日期">{{date(detail.paymentDate)}}</el-descriptions-item><el-descriptions-item label="方式">{{methodText[detail.method]??detail.method}}</el-descriptions-item><el-descriptions-item label="经办人">{{detail.operator?.displayName??'—'}}</el-descriptions-item><el-descriptions-item label="交易参考号">{{detail.externalReference??'—'}}</el-descriptions-item><el-descriptions-item label="备注">{{detail.remark??'—'}}</el-descriptions-item></el-descriptions></el-card></div>
        <el-card shadow="never"><template #header><b>操作痕迹</b></template><el-timeline><el-timeline-item v-for="(log,index) in detail.operationLogs" :key="index" :timestamp="String(log.occurredAt??'')">{{log.action??log.operationType??'操作记录'}}</el-timeline-item></el-timeline><el-empty v-if="!detail.operationLogs.length" description="暂无操作记录" /></el-card>
      </div><el-empty v-else class="empty-detail" description="请选择一条收款记录" />
    </div>

    <el-dialog v-model="refundOpen" title="申请退款" width="640px"><el-alert title="退款提交后不会立即冲减账单，需超级管理员确认。" type="warning" :closable="false"/><el-form label-position="top" class="dialog-form"><el-row :gutter="14"><el-col :span="8"><el-form-item label="退款金额"><el-input v-model="refund.refundAmount"/></el-form-item></el-col><el-col :span="8"><el-form-item label="退款日期"><el-date-picker v-model="refund.refundDate" type="date" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="退款方式"><el-select v-model="refund.refundMethod" style="width:100%"><el-option v-for="(label,value) in methodText" :key="value" :value="value" :label="label"/></el-select></el-form-item></el-col></el-row><el-form-item label="原因"><el-input v-model="refund.reason" type="textarea"/></el-form-item><b>退款分配明细</b><div v-for="allocation in detail?.allocations" :key="allocation.id" class="refund-line"><span>第 {{allocation.bill.periodSeq}} 期（可退 {{money(allocation.effectiveAmount)}}）</span><el-input v-model="refund.allocations[allocation.id]" style="width:150px"/></div></el-form><template #footer><el-button @click="refundOpen=false">取消</el-button><el-button type="primary" @click="submitRefund">提交退款申请</el-button></template></el-dialog>
    <el-dialog v-model="voidOpen" title="申请作废收款" width="520px"><el-alert title="确认后将冲回账期分配、预收款及关联优惠，请谨慎操作。" type="error" :closable="false"/><el-input v-model="voidReason" type="textarea" maxlength="500" placeholder="请输入作废原因" class="dialog-form"/><template #footer><el-button @click="voidOpen=false">取消</el-button><el-button type="danger" @click="submitVoid">提交作废申请</el-button></template></el-dialog>
    <el-dialog v-model="editOpen" title="更正收款信息" width="620px"><el-alert title="票据号和合同不可修改；保存后将重新计算账期分配并记录修改前后内容。" type="warning" :closable="false"/><el-form label-position="top" class="dialog-form"><el-row :gutter="14"><el-col :span="12"><el-form-item label="收款日期"><el-date-picker v-model="edit.paymentDate" type="date" value-format="YYYY-MM-DD" format="YYYY年MM月DD日" style="width:100%"/></el-form-item></el-col><el-col :span="12"><el-form-item label="金额"><el-input v-model="edit.amount"/></el-form-item></el-col><el-col :span="12"><el-form-item label="方式"><el-select v-model="edit.method" style="width:100%"><el-option v-for="(label,value) in methodText" :key="value" :value="value" :label="label"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="交易参考号"><el-input v-model="edit.externalReference"/></el-form-item></el-col></el-row><el-form-item label="备注"><el-input v-model="edit.remark"/></el-form-item><el-form-item label="修改原因（必填）"><el-input v-model="edit.editReason" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="editOpen=false">取消</el-button><el-button type="primary" @click="submitEdit">保存更正</el-button></template></el-dialog>
  </PaymentWorkspace>
</template>

<style scoped>
.filter-card :deep(.el-form-item){margin-bottom:0}.detail-layout{display:grid;grid-template-columns:300px minmax(0,1fr);gap:16px;align-items:start}.record-list{position:sticky;top:88px}.record-list :deep(.el-card__body){padding:0}.record-item{display:flex;width:100%;justify-content:space-between;gap:10px;padding:14px 16px;border:0;border-bottom:1px solid #edf0f4;background:#fff;color:#344258;text-align:left;cursor:pointer}.record-item:hover,.record-item.active{background:#edf4ff}.record-item span{display:grid;gap:5px}.record-item span:last-child{text-align:right}.record-item small{color:#8b98aa}.detail-content{display:grid;gap:16px}.receipt-head{display:flex;justify-content:space-between;gap:15px}.receipt-head h2{margin:10px 0 5px}.receipt-head p{margin:0;color:#78879b}.actions{display:flex;flex-wrap:wrap;align-content:flex-start;gap:7px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:20px}.metrics div{display:grid;gap:8px;padding:15px;border-radius:9px;background:#f5f7fb}.metrics small{color:#7e8b9e}.metrics b{font-size:19px}.detail-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px}.file-row,.refund-line{display:flex;justify-content:space-between;align-items:center;padding:10px 0;border-bottom:1px solid #edf0f5}.dialog-form{margin-top:18px}.empty-detail{padding:70px;background:#fff;border-radius:10px}.receipt-tags{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:1100px){.detail-layout{grid-template-columns:1fr}.record-list{position:static}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.detail-columns{grid-template-columns:1fr}.receipt-head{flex-direction:column}}
@media print{.filter-card,.record-list,.actions{display:none!important}.detail-layout{display:block}.detail-content>:not(:first-child){display:none}.receipt-head{display:block}}
</style>
