CREATE TABLE `bill_adjustments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adjustment_no` VARCHAR(40) NOT NULL,
  `rent_bill_id` INT UNSIGNED NOT NULL,
  `adjustment_type` ENUM('DISCOUNT','WAIVER','INCREASE','CORRECTION') NOT NULL,
  `direction` ENUM('DECREASE','INCREASE') NOT NULL,
  `amount` DECIMAL(14,2) NOT NULL,
  `before_amount` DECIMAL(14,2) NOT NULL,
  `after_amount` DECIMAL(14,2) NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `source_payment_id` INT UNSIGNED NULL,
  `contract_change_id` INT UNSIGNED NULL,
  `approval_status` ENUM('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `submitted_by` INT UNSIGNED NOT NULL,
  `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `approved_by` INT UNSIGNED NULL,
  `approved_at` DATETIME(3) NULL,
  `rejected_reason` VARCHAR(500) NULL,
  `reversed_by_adjustment_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  KEY `bill_adjustments_rent_bill_id_approval_status_idx` (`rent_bill_id`, `approval_status`),
  KEY `bill_adjustments_adjustment_no_idx` (`adjustment_no`),
  CONSTRAINT `bill_adjustments_rent_bill_id_fkey` FOREIGN KEY (`rent_bill_id`) REFERENCES `rent_bills`(`id`),
  CONSTRAINT `bill_adjustments_source_payment_id_fkey` FOREIGN KEY (`source_payment_id`) REFERENCES `payments`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `payment_refunds` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `refund_no` VARCHAR(40) NOT NULL,
  `payment_id` INT UNSIGNED NOT NULL,
  `contract_id` INT UNSIGNED NOT NULL,
  `refund_amount` DECIMAL(14,2) NOT NULL,
  `refund_date` DATE NOT NULL,
  `refund_method` ENUM('WECHAT','ALIPAY','BANK_TRANSFER','CASH','POS','OTHER') NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `approval_status` ENUM('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `submitted_by` INT UNSIGNED NOT NULL,
  `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `approved_by` INT UNSIGNED NULL,
  `approved_at` DATETIME(3) NULL,
  `rejected_reason` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_refunds_refund_no_key` (`refund_no`),
  KEY `payment_refunds_payment_id_approval_status_idx` (`payment_id`, `approval_status`),
  CONSTRAINT `payment_refunds_payment_id_fkey` FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`),
  CONSTRAINT `payment_refunds_contract_id_fkey` FOREIGN KEY (`contract_id`) REFERENCES `contracts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `payment_void_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_no` VARCHAR(40) NOT NULL,
  `payment_id` INT UNSIGNED NOT NULL,
  `reason` VARCHAR(500) NOT NULL,
  `approval_status` ENUM('DRAFT','PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `submitted_by` INT UNSIGNED NOT NULL,
  `submitted_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `approved_by` INT UNSIGNED NULL,
  `approved_at` DATETIME(3) NULL,
  `rejected_reason` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_void_requests_request_no_key` (`request_no`),
  KEY `payment_void_requests_payment_id_approval_status_idx` (`payment_id`, `approval_status`),
  CONSTRAINT `payment_void_requests_payment_id_fkey` FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
