<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { http } from '../services/http'
import { useSessionStore } from '../stores/session'
const session = useSessionStore(); const contracts = ref<any[]>([]); const settlements = ref<any[]>([]); const deposits = ref<any>({ balance: 0, items: [] }); const refunds = ref<any[]>([]); const bills = ref<any[]>([]); const proofFileIds = ref<number[]>([])
const isSuper = computed(() => session.user?.role === 'SUPER_ADMIN')
const depositForm = reactive({ contractId: undefined as number | undefined, paymentDate: new Date().toISOString().slice(0, 10), amount: '', method: 'WECHAT', externalReference: '', remark: '' })
const checkoutForm = reactive({ contractId: undefined as number | undefined, checkoutType: '提前退租', plannedCheckoutDate: new Date().toISOString().slice(0, 10), handoverDate: new Date().toISOString().slice(0, 10), inspectionAt: new Date().toISOString().slice(0, 10), checkoutReason: '', targetRoomStatus: 'EMPTY' })
const settlementForm = reactive({ actualCheckoutDate: new Date().toISOString().slice(0, 10), handoverDate: new Date().toISOString().slice(0, 10), inspectionAt: new Date().toISOString().slice(0, 10), targetRoomStatus: 'EMPTY', remark: '', items: [] as any[] })
const refundForm = reactive({ checkoutSettlementId: undefined as number | undefined, refundAmount: '', refundDate: new Date().toISOString().slice(0, 10), refundMethod: 'WECHAT', remark: '' })
async function load() { contracts.value = (await http.get('/contracts')).data.data; settlements.value = (await http.get('/checkout-settlements')).data.data }
async function selectContract() { if (!depositForm.contractId) return; deposits.value = (await http.get('/deposits', { params: { contractId: depositForm.contractId } })).data.data; bills.value = (await http.get(`/contracts/${depositForm.contractId}/bills`)).data.data; refunds.value = (await http.get('/deposit-refunds', { params: { contractId: depositForm.contractId } })).data.data }
async function recordDeposit() { if (!depositForm.contractId || !depositForm.amount) return alert('请选择合同并填写押金金额'); await http.post('/deposits', depositForm); await selectContract(); depositForm.amount = ''; alert('押金收取已登记') }
async function initiate() { if (!checkoutForm.contractId || !checkoutForm.checkoutReason) return alert('请选择合同并填写退租原因'); await http.post(`/checkout-settlements/contract/${checkoutForm.contractId}/initiate`, checkoutForm); await load(); alert('已发起退租，未来账单尚未作废') }
function addArrears() { settlementForm.items.push({ itemType: 'RENT_ARREARS', amount: '', rentBillId: undefined, inspectionRecordRef: '', description: '欠租', evidenceRequired: false, confirmedByTenant: true }) }
function addDeduction() { settlementForm.items.push({ itemType: 'REPAIR', amount: '', rentBillId: undefined, inspectionRecordRef: '', description: '', evidenceRequired: true, confirmedByTenant: true }) }
async function submitSettlement(row: any) { await http.post(`/checkout-settlements/${row.id}/submit`, settlementForm); await load(); alert('结算单已提交，等待超级管理员确认') }
async function approveSettlement(id: number) { await http.post(`/checkout-settlements/${id}/approve`); await load() }
async function uploadProof(file: any) { const data = new FormData(); data.append('file', file.file); const result = await http.post('/deposit-refunds/proof-files', data); proofFileIds.value.push(result.data.data.id); return false }
async function submitRefund() { if (!refundForm.checkoutSettlementId || !refundForm.refundAmount || !proofFileIds.value.length) return alert('请填写退款信息并上传至少一份凭证'); await http.post('/deposit-refunds', { ...refundForm, proofFileIds: proofFileIds.value }); proofFileIds.value = []; await selectContract(); await load(); alert('押金退款已登记，等待超级管理员确认') }
async function approveRefund(id: number) { await http.post(`/deposit-refunds/${id}/approve`); await load(); await selectContract() }
onMounted(load)
</script>
<template><main class="users-page"><header><div><el-tag>Task010</el-tag><h1>押金与退租结算</h1><p>流程：发起退租 → 验房结算 → 押金退还确认。发起时不会作废未来账单，确认结算后才处理。</p></div></header>
<el-card header="押金收取"><el-form label-position="top"><el-row :gutter="12"><el-col :span="8"><el-form-item label="合同"><el-select v-model="depositForm.contractId" @change="selectContract"><el-option v-for="item in contracts" :key="item.id" :label="item.contractNo" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="6"><el-form-item label="收取日期"><el-date-picker v-model="depositForm.paymentDate" value-format="YYYY-MM-DD" type="date" /></el-form-item></el-col><el-col :span="5"><el-form-item label="金额"><el-input v-model="depositForm.amount" /></el-form-item></el-col><el-col :span="5"><el-form-item label="方式"><el-select v-model="depositForm.method"><el-option label="微信" value="WECHAT" /><el-option label="支付宝" value="ALIPAY" /><el-option label="银行转账" value="BANK_TRANSFER" /><el-option label="现金" value="CASH" /></el-select></el-form-item></el-col></el-row></el-form><el-button type="primary" @click="recordDeposit">登记押金收取</el-button><el-tag v-if="depositForm.contractId" style="margin-left:12px">当前押金余额：{{ deposits.balance }}</el-tag></el-card>
<el-card header="发起退租" style="margin-top:16px"><el-form label-position="top"><el-row :gutter="12"><el-col :span="8"><el-form-item label="合同"><el-select v-model="checkoutForm.contractId"><el-option v-for="item in contracts.filter((item:any)=>item.status==='ACTIVE')" :key="item.id" :label="item.contractNo" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="退租类型"><el-input v-model="checkoutForm.checkoutType" /></el-form-item></el-col><el-col :span="8"><el-form-item label="计划退房日"><el-date-picker v-model="checkoutForm.plannedCheckoutDate" value-format="YYYY-MM-DD" type="date" /></el-form-item></el-col><el-col :span="8"><el-form-item label="交接日"><el-date-picker v-model="checkoutForm.handoverDate" value-format="YYYY-MM-DD" type="date" /></el-form-item></el-col><el-col :span="8"><el-form-item label="验房日"><el-date-picker v-model="checkoutForm.inspectionAt" value-format="YYYY-MM-DD" type="date" /></el-form-item></el-col><el-col :span="8"><el-form-item label="退房后房态"><el-select v-model="checkoutForm.targetRoomStatus"><el-option label="空置" value="EMPTY" /><el-option label="维修中" value="MAINTENANCE" /><el-option label="停用" value="DISABLED" /></el-select></el-form-item></el-col><el-col :span="24"><el-form-item label="退租原因"><el-input v-model="checkoutForm.checkoutReason" /></el-form-item></el-col></el-row></el-form><el-button type="warning" @click="initiate">发起退租</el-button></el-card>
<el-card header="退租结算与审批" style="margin-top:16px"><el-table :data="settlements"><el-table-column prop="settlementNo" label="结算编号" /><el-table-column prop="contract.contractNo" label="合同" /><el-table-column prop="status" label="状态" /><el-table-column prop="depositRefundableAmount" label="应退押金" /><el-table-column prop="finalReceivable" label="待补交" /><el-table-column label="操作"><template #default="{ row }"><el-button v-if="row.status==='DRAFT'" size="small" @click="addArrears">添加欠租项目</el-button><el-button v-if="row.status==='DRAFT'" size="small" @click="addDeduction">添加扣款</el-button><el-button v-if="row.status==='DRAFT'" size="small" type="primary" @click="submitSettlement(row)">提交结算</el-button><el-button v-if="row.status==='PENDING' && isSuper" size="small" type="success" @click="approveSettlement(row.id)">确认结算</el-button></template></el-table-column></el-table><el-table v-if="settlementForm.items.length" :data="settlementForm.items" style="margin-top:12px"><el-table-column label="类型"><template #default="{ row }"><el-select v-model="row.itemType"><el-option label="欠租" value="RENT_ARREARS" /><el-option label="维修" value="REPAIR" /><el-option label="损坏" value="DAMAGE" /><el-option label="清洁" value="CLEANING" /><el-option label="其他" value="OTHER" /></el-select></template></el-table-column><el-table-column label="金额"><template #default="{ row }"><el-input v-model="row.amount" /></template></el-table-column><el-table-column label="账单/验收依据"><template #default="{ row }"><el-select v-if="row.itemType==='RENT_ARREARS'" v-model="row.rentBillId"><el-option v-for="bill in bills" :key="bill.id" :label="`第${bill.periodSeq}期`" :value="bill.id" /></el-select><el-input v-else v-model="row.inspectionRecordRef" placeholder="验收记录引用" /></template></el-table-column><el-table-column label="说明"><template #default="{ row }"><el-input v-model="row.description" /></template></el-table-column></el-table></el-card>
<el-card header="押金退款" style="margin-top:16px"><el-form label-position="top"><el-row :gutter="12"><el-col :span="8"><el-form-item label="已确认结算单"><el-select v-model="refundForm.checkoutSettlementId"><el-option v-for="item in settlements.filter((item:any)=>item.status==='APPROVED' && Number(item.depositRefundableAmount)>0)" :key="item.id" :label="item.settlementNo" :value="item.id" /></el-select></el-form-item></el-col><el-col :span="6"><el-form-item label="退款金额"><el-input v-model="refundForm.refundAmount" /></el-form-item></el-col><el-col :span="5"><el-form-item label="退款日期"><el-date-picker v-model="refundForm.refundDate" value-format="YYYY-MM-DD" type="date" /></el-form-item></el-col><el-col :span="5"><el-form-item label="退款方式"><el-select v-model="refundForm.refundMethod"><el-option label="微信" value="WECHAT" /><el-option label="支付宝" value="ALIPAY" /><el-option label="银行转账" value="BANK_TRANSFER" /><el-option label="现金" value="CASH" /></el-select></el-form-item></el-col></el-row></el-form><el-upload :auto-upload="false" :show-file-list="false" :on-change="uploadProof"><el-button>上传退款凭证</el-button></el-upload><span style="margin-left:12px">已上传 {{ proofFileIds.length }} 份</span><el-button type="primary" style="margin-left:12px" @click="submitRefund">登记退款</el-button><el-table :data="refunds" style="margin-top:12px"><el-table-column prop="refundNo" label="退款编号" /><el-table-column prop="refundAmount" label="金额" /><el-table-column prop="approvalStatus" label="状态" /><el-table-column v-if="isSuper" label="审批"><template #default="{ row }"><el-button v-if="row.approvalStatus==='PENDING'" size="small" type="success" @click="approveRefund(row.id)">确认退款并结束合同</el-button></template></el-table-column></el-table></el-card></main></template>
