<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { http } from '../services/http'
import { useSessionStore } from '../stores/session'
const router = useRouter(); const session = useSessionStore(); const data = ref<any>({ roomSummary:{statusCounts:{},rooms:[]},rentReminders:[],arrears:[],expiringContracts:[],approvals:{} }); const buildings = ref<any[]>([])
const filters = reactive({ buildingId: undefined as number|undefined, statuses: [] as string[] })
const isSuper = computed(()=>session.user?.role==='SUPER_ADMIN')
const labels:Record<string,string>={EMPTY:'空置',PENDING_MOVE_IN:'待入住',RENTED:'已出租',PENDING_CHECKOUT:'待退房',MAINTENANCE:'维修中',FOR_SALE:'待出售',SOLD:'已出售',DISABLED:'停用',OTHER:'其他'}
async function load(){ const params:any={}; if(filters.buildingId)params.buildingId=filters.buildingId; if(filters.statuses.length)params.statuses=filters.statuses.join(','); data.value=(await http.get('/dashboard',{params})).data.data }
async function init(){ buildings.value=(await http.get('/properties/buildings')).data.data; await load() }
onMounted(init)
</script>
<template><main class="users-page dashboard-page"><header><div><el-tag type="primary">驾驶舱</el-tag><h1>经营概览</h1><p>快速查看房态、租金待办与合同履行情况。</p></div><div><el-button type="primary" @click="router.push('/payments')">登记收款</el-button><el-button @click="router.push('/contracts')">合同管理</el-button></div></header>
<el-card class="dashboard-filter"><el-form inline><el-form-item label="楼栋"><el-select v-model="filters.buildingId" clearable placeholder="全部楼栋" @change="load"><el-option v-for="item in buildings" :key="item.id" :label="item.buildingName" :value="item.id" /></el-select></el-form-item><el-form-item label="房态"><el-select v-model="filters.statuses" multiple collapse-tags clearable placeholder="全部房态" @change="load"><el-option v-for="(label,key) in labels" :key="key" :label="label" :value="key" /></el-select></el-form-item><el-button @click="load">刷新</el-button></el-form></el-card>
<section class="metric-grid"><el-card><el-statistic title="房源总数" :value="data.roomSummary.total||0" /><p>可经营 {{ data.roomSummary.operating||0 }} 套</p></el-card><el-card><el-statistic title="已出租" :value="data.roomSummary.rented||0" /><p>出租率 {{ data.roomSummary.occupancyRate===null?'—':`${data.roomSummary.occupancyRate}%` }}</p></el-card><el-card><el-statistic :title="`未来 ${data.rentReminderDays||7} 天催租`" :value="data.rentReminders.length" /><p>待收款账单提醒</p></el-card><el-card><el-statistic title="逾期欠租" :value="data.arrears.length" /><p v-if="isSuper">欠租金额 {{ data.arrearsTotal||0 }}</p><p v-else>待跟进账单</p></el-card><el-card><el-statistic :title="`空置超过 ${data.longVacancyDays||30} 天`" :value="data.longVacancyRooms?.length||0" /><p>建议优先跟进招租</p></el-card></section>
<section class="dashboard-columns"><el-card header="待办事项"><el-descriptions :column="1" border><el-descriptions-item label="账单调整待审批">{{ data.approvals.billAdjustments||0 }}</el-descriptions-item><el-descriptions-item label="收款退款待审批">{{ data.approvals.paymentRefunds||0 }}</el-descriptions-item><el-descriptions-item label="阶梯退差待审批">{{ data.approvals.pricingRebates||0 }}</el-descriptions-item><el-descriptions-item :label="`${data.contractExpiryDays||30} 天内合同到期`">{{ data.expiringContracts.length }}</el-descriptions-item></el-descriptions></el-card><el-card header="房态分布"><div class="status-tags"><el-tag v-for="(count,status) in data.roomSummary.statusCounts" :key="String(status)" effect="plain">{{ labels[String(status)] }} {{ count }}</el-tag></div><div class="room-grid"><div v-for="room in data.roomSummary.rooms" :key="room.id" class="room-cell" :class="`status-${room.roomStatus}`"><strong>{{ room.fullHouseNo }}</strong><span>{{ labels[room.roomStatus] }}</span></div></div></el-card></section>
<section class="dashboard-columns"><el-card :header="`未来 ${data.rentReminderDays||7} 天催租`"><el-empty v-if="!data.rentReminders.length" description="暂无催租事项" /><el-table v-else :data="data.rentReminders" size="small"><el-table-column prop="contract.room.fullHouseNo" label="房号" /><el-table-column prop="dueDate" label="应缴日" /><el-table-column prop="outstandingAmount" label="未收金额" /><el-table-column label="承租人"><template #default="{row}">{{row.contract.members?.[0]?.tenant?.name}}</template></el-table-column></el-table></el-card><el-card header="逾期欠租"><el-empty v-if="!data.arrears.length" description="暂无逾期欠租" /><el-table v-else :data="data.arrears" size="small"><el-table-column prop="contract.room.fullHouseNo" label="房号" /><el-table-column prop="dueDate" label="应缴日" /><el-table-column prop="outstandingAmount" label="未收金额" /><el-table-column label="承租人"><template #default="{row}">{{row.contract.members?.[0]?.tenant?.name}}</template></el-table-column></el-table></el-card></section><section><el-card :header="`长期空置预警（超过 ${data.longVacancyDays||30} 天）`"><el-empty v-if="!data.longVacancyRooms?.length" description="暂无长期空置房源" /><el-table v-else :data="data.longVacancyRooms" size="small"><el-table-column prop="fullHouseNo" label="房号" /><el-table-column prop="building.buildingName" label="楼栋" /><el-table-column prop="statusChangedAt" label="空置起始时间" /></el-table></el-card></section></main></template>
<style scoped>.dashboard-filter{margin-bottom:16px}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.metric-grid p{margin:8px 0 0;color:#8f959e;font-size:13px}.dashboard-columns{display:grid;grid-template-columns:1fr 1.6fr;gap:16px;margin-bottom:16px}.status-tags{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.room-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(92px,1fr));gap:8px;max-height:240px;overflow:auto}.room-cell{padding:9px;border-radius:6px;background:#f5f6f7;font-size:12px;display:flex;flex-direction:column;gap:4px}.room-cell span{color:#646a73}.status-RENTED{background:#e8f3ff}.status-EMPTY{background:#f5f6f7}.status-PENDING_CHECKOUT{background:#fff4e5}.status-MAINTENANCE{background:#fff1f0}@media(max-width:900px){.metric-grid,.dashboard-columns{grid-template-columns:1fr 1fr}}@media(max-width:600px){.metric-grid,.dashboard-columns{grid-template-columns:1fr}}</style>
