<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { http } from '../services/http'
const collection = ref<any>({ rows: [], total: {} }); const cash = ref<any>({ flows: [] }); const commissions = ref<any[]>([]); const contracts = ref<any[]>([]); const exportTasks = ref<any[]>([])
const filters = reactive({ from: '', to: '' }); const commissionForm = reactive({ contractId: undefined as number | undefined, recipientName: '', amount: '' })
async function load() { const params = { ...(filters.from ? { from: filters.from } : {}), ...(filters.to ? { to: filters.to } : {}) }; const [a,b,c,d,e] = await Promise.all([http.get('/finance/rent-collection',{params}),http.get('/finance/cash-flows',{params}),http.get('/commissions'),http.get('/contracts'),http.get('/finance/export-tasks')]); collection.value=a.data.data; cash.value=b.data.data; commissions.value=c.data.data; contracts.value=d.data.data; exportTasks.value=e.data.data }
async function createCommission() { if (!commissionForm.contractId || !commissionForm.recipientName || commissionForm.amount==='') return alert('请完整填写提成信息'); await http.post('/commissions', commissionForm); commissionForm.recipientName=''; commissionForm.amount=''; await load() }
async function removeCommission(id:number) { if (confirm('确认删除该提成登记吗？')) { await http.delete(`/commissions/${id}`); await load() } }
async function createExportTask(reportType: 'overview' | 'rent-collection' | 'cash-flows' | 'commissions', format: 'XLSX' | 'PDF') { await http.post('/finance/export-tasks', { reportType, format, ...(filters.from ? { from: filters.from } : {}), ...(filters.to ? { to: filters.to } : {}) }); ElMessage.success('导出任务已创建，请在下方任务列表下载'); await load() }
async function downloadExport(reportType: 'overview' | 'rent-collection' | 'cash-flows' | 'commissions', extension: 'xlsx' | 'pdf') { return createExportTask(reportType, extension.toUpperCase() as 'XLSX' | 'PDF') }
async function downloadTask(id: number, name: string) { const response = await http.get(`/finance/export-tasks/${id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url) }
onMounted(load)
</script>
<template><main class="users-page"><header><div><el-tag>Task011</el-tag><h1>财务中心</h1><p>账期经营口径与资金收付口径分开展示。押金和未分配预收款不计入租金收入。</p></div></header>
<el-card header="筛选与异步导出"><el-form inline><el-form-item label="开始日期"><el-date-picker v-model="filters.from" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="filters.to" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="createExportTask('overview','PDF')">导出财务总览 PDF</el-button><el-button @click="createExportTask('rent-collection','XLSX')">导出租金收缴 Excel</el-button><el-button @click="createExportTask('rent-collection','PDF')">导出租金收缴 PDF</el-button><el-button @click="createExportTask('cash-flows','XLSX')">导出资金流水 Excel</el-button><el-button @click="createExportTask('cash-flows','PDF')">导出资金流水 PDF</el-button></el-form><el-table :data="exportTasks" size="small" style="margin-top:12px"><el-table-column prop="taskNo" label="任务编号" min-width="180" /><el-table-column prop="reportType" label="报表" /><el-table-column prop="exportFormat" label="格式" /><el-table-column prop="status" label="状态" /><el-table-column prop="createdAt" label="创建时间" min-width="180" /><el-table-column label="操作"><template #default="{row}"><el-button v-if="row.status === 'SUCCESS'" link type="primary" @click="downloadTask(row.id, row.fileAsset.originalName)">下载</el-button><span v-else-if="row.status === 'FAILED'">失败：{{ row.failureReason }}</span><span v-else>处理中</span></template></el-table-column></el-table></el-card>
<el-card header="租金收缴（按账期）" style="margin-top:16px"><el-row :gutter="12"><el-col :span="4"><el-statistic title="原应收" :value="Number(collection.total.originalReceivable || 0)" :precision="2" /></el-col><el-col :span="4"><el-statistic title="优惠减免" :value="Number(collection.total.concessionAmount || 0)" :precision="2" /></el-col><el-col :span="4"><el-statistic title="净应收" :value="Number(collection.total.netReceivable || 0)" :precision="2" /></el-col><el-col :span="4"><el-statistic title="有效实收" :value="Number(collection.total.validReceived || 0)" :precision="2" /></el-col><el-col :span="4"><el-statistic title="未收" :value="Number(collection.total.outstanding || 0)" :precision="2" /></el-col><el-col :span="4"><el-statistic title="收租率" :value="collection.collectionRate === null ? 0 : Number(collection.collectionRate)" suffix="%" :precision="2" /></el-col></el-row><el-table :data="collection.rows" style="margin-top:16px"><el-table-column prop="billNo" label="账单" /><el-table-column prop="contractNo" label="合同" /><el-table-column prop="houseNo" label="房号" /><el-table-column prop="tenantName" label="承租人" /><el-table-column prop="originalReceivable" label="原应收" /><el-table-column prop="concessionAmount" label="优惠减免" /><el-table-column prop="netReceivable" label="净应收" /><el-table-column prop="validReceived" label="有效实收" /><el-table-column prop="outstanding" label="未收" /><el-table-column prop="status" label="状态" /></el-table></el-card>
<el-card header="资金流水（按实际发生日）" style="margin-top:16px"><el-row :gutter="16"><el-col :span="8"><el-statistic title="外部流入" :value="Number(cash.inflow || 0)" :precision="2" /></el-col><el-col :span="8"><el-statistic title="外部流出" :value="Number(cash.outflow || 0)" :precision="2" /></el-col><el-col :span="8"><el-statistic title="净资金流" :value="Number(cash.netCashFlow || 0)" :precision="2" /></el-col></el-row><el-table :data="cash.flows" style="margin-top:16px"><el-table-column prop="date" label="日期" /><el-table-column prop="type" label="类型" /><el-table-column prop="amount" label="金额" /><el-table-column prop="direction" label="方向" /><el-table-column label="外部现金流"><template #default="{row}">{{ row.external ? '是' : '否（内部抵扣）' }}</template></el-table-column><el-table-column label="计入租金实收"><template #default="{row}">{{ row.countsAsRentReceipt ? '是' : '否' }}</template></el-table-column><el-table-column prop="reference" label="业务编号" /></el-table></el-card>
<el-card header="租房提成台账" style="margin-top:16px"><el-button style="margin-bottom:12px" @click="downloadExport('commissions','xlsx')">导出提成台账 Excel</el-button><el-alert title="提成仅为内部登记，不代表已付款，不影响租金、押金、预收款或资金流水。" type="info" :closable="false" /><el-form inline style="margin-top:12px"><el-form-item label="合同"><el-select v-model="commissionForm.contractId"><el-option v-for="item in contracts" :key="item.id" :label="item.contractNo" :value="item.id" /></el-select></el-form-item><el-form-item label="所属对象"><el-input v-model="commissionForm.recipientName" /></el-form-item><el-form-item label="金额"><el-input v-model="commissionForm.amount" /></el-form-item><el-button type="primary" @click="createCommission">新增</el-button></el-form><el-table :data="commissions"><el-table-column prop="contract.contractNo" label="合同" /><el-table-column prop="recipientName" label="所属对象" /><el-table-column prop="amount" label="金额" /><el-table-column label="操作"><template #default="{row}"><el-button size="small" type="danger" @click="removeCommission(row.id)">删除</el-button></template></el-table-column></el-table></el-card></main></template>
