<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { http } from '../services/http'

const tab = ref('settings'); const settings = reactive<any>({}); const logs = ref<any[]>([]); const audits = ref<any[]>([]); const verification = ref<any>(); const backups = ref<any[]>([])
async function loadSettings(){ Object.assign(settings,(await http.get('/admin/settings')).data.data) }
async function saveSettings(){ await http.put('/admin/settings', settings); ElMessage.success('系统参数已保存') }
async function loadLogs(){ logs.value=(await http.get('/admin/operation-logs')).data.data }
async function loadAudits(){ audits.value=(await http.get('/admin/security-audits')).data.data; verification.value=(await http.get('/admin/security-audits/verify')).data.data }
async function loadBackups(){ backups.value=(await http.get('/admin/backups')).data.data }
async function backup(){ const result = (await http.post('/admin/backups')).data.data; ElMessage[result.status === 'SUCCESS' ? 'success' : 'error'](result.status === 'SUCCESS' ? '数据库与附件备份已完成' : `备份失败：${result.failureReason || '请查看备份记录'}`); await loadBackups() }
async function restoreBackup(row:any){ const { value: reason } = await ElMessageBox.prompt('请填写恢复原因','恢复数据库',{inputValidator:(v)=>v?.trim()?true:'必须填写原因'}); const { value: confirmation } = await ElMessageBox.prompt('输入“确认恢复”继续。恢复将覆盖当前数据库并让所有用户重新登录。','二次确认',{inputValidator:(v)=>v==='确认恢复'||'请输入“确认恢复”'}); await http.post(`/admin/backups/${row.id}/restore`,{reason,confirmation}); ElMessage.success('恢复已完成，请重新登录'); await loadBackups() }
async function hide(row:any){ const {value}=await ElMessageBox.prompt('请填写隐藏原因（日志不会被删除）','隐藏操作日志',{inputValidator:(v)=>v?.trim()?true:'必须填写原因'}); await http.post(`/admin/operation-logs/${row.id}/hide`,{reason:value}); ElMessage.success('日志已隐藏'); await loadLogs() }
async function restore(row:any){ const {value}=await ElMessageBox.prompt('请填写恢复原因','恢复操作日志',{inputValidator:(v)=>v?.trim()?true:'必须填写原因'}); await http.post(`/admin/operation-logs/${row.id}/restore`,{reason:value}); ElMessage.success('日志已恢复'); await loadLogs() }
onMounted(async()=>{ await Promise.all([loadSettings(),loadLogs(),loadAudits(),loadBackups()]) })
</script>
<template><main class="users-page"><header><div><el-tag type="primary">系统管理</el-tag><h1>系统设置与安全审计</h1><p>仅超级管理员可修改系统参数、管理日志和发起受控备份。</p></div></header>
<el-tabs v-model="tab" class="system-tabs">
<el-tab-pane label="系统参数" name="settings"><el-card><el-alert title="租金金额口径、角色权限、审批流程和审计保留规则属于冻结业务基线，不可在此处修改。" type="info" :closable="false" show-icon/><el-form label-width="160px" class="settings-form"><el-form-item label="项目名称"><el-input v-model="settings.projectName" /></el-form-item><el-form-item label="租金提醒（天）"><el-input-number v-model="settings.rentReminderDays" :min="1" :max="90" /></el-form-item><el-form-item label="合同到期提醒（天）"><el-input-number v-model="settings.contractExpiryDays" :min="1" :max="365" /></el-form-item><el-form-item label="长期空置预警（天）"><el-input-number v-model="settings.longVacancyDays" :min="1" :max="365" /></el-form-item><el-form-item label="收据编号前缀"><el-input v-model="settings.receiptPrefix" /></el-form-item><el-form-item label="上传大小上限（MB）"><el-input-number v-model="settings.uploadSizeLimitMb" :min="1" :max="100" /></el-form-item><el-form-item label="默认租客类型"><el-radio-group v-model="settings.defaultTenantType"><el-radio value="INDIVIDUAL">个人</el-radio><el-radio value="COMPANY">企业</el-radio></el-radio-group></el-form-item><el-form-item label="默认付款周期"><el-select v-model="settings.defaultPaymentCycle"><el-option label="月付" value="MONTHLY"/><el-option label="季付" value="QUARTERLY"/><el-option label="半年付" value="HALF_YEARLY"/><el-option label="年付" value="YEARLY"/></el-select></el-form-item><el-button type="primary" @click="saveSettings">保存参数</el-button></el-form></el-card></el-tab-pane>
<el-tab-pane label="操作日志" name="logs"><el-card><template #header><div class="card-header"><span>操作日志（隐藏不等于删除）</span><el-button @click="loadLogs">刷新</el-button></div></template><el-table :data="logs"><el-table-column prop="occurredAt" label="时间" width="190"/><el-table-column prop="module" label="模块" width="110"/><el-table-column prop="action" label="操作" width="180"/><el-table-column prop="summary" label="摘要"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag v-if="row.isHidden" type="info">已隐藏</el-tag><span v-else>正常</span></template></el-table-column><el-table-column label="处理" width="120"><template #default="{row}"><el-button v-if="!row.isHidden" link type="danger" @click="hide(row)">隐藏</el-button><el-button v-else link type="primary" @click="restore(row)">恢复</el-button></template></el-table-column></el-table></el-card></el-tab-pane>
<el-tab-pane label="安全审计" name="audits"><el-card><template #header><div class="card-header"><span>不可修改安全审计</span><el-button @click="loadAudits">验证完整性</el-button></div></template><el-alert :title="verification?.valid ? `审计链完整，共 ${verification.total} 条记录` : `发现异常记录：${verification?.invalidIds?.join('、')}`" :type="verification?.valid?'success':'error'" :closable="false" show-icon/><el-table :data="audits" style="margin-top:16px"><el-table-column prop="occurredAt" label="时间" width="190"/><el-table-column prop="eventType" label="事件"/><el-table-column prop="entityType" label="对象"/><el-table-column prop="operatorId" label="操作人 ID"/><el-table-column prop="recordHash" label="完整性哈希" show-overflow-tooltip/></el-table></el-card></el-tab-pane>
<el-tab-pane label="备份与恢复" name="backups"><el-card><template #header><div class="card-header"><span>备份与恢复</span><el-button type="primary" @click="backup">创建手工备份</el-button></div></template><el-alert title="恢复会先备份当前数据库，必须填写原因并二次确认；完成后所有用户需要重新登录。" type="warning" :closable="false" show-icon/><el-table :data="backups" style="margin-top:16px"><el-table-column prop="backupNo" label="备份编号"/><el-table-column prop="backupType" label="类型" width="120"/><el-table-column prop="status" label="状态" width="120"/><el-table-column prop="createdAt" label="创建时间" width="190"/><el-table-column prop="failureReason" label="说明"/><el-table-column label="操作" width="120"><template #default="{row}"><el-button v-if="row.status==='SUCCESS'" link type="danger" @click="restoreBackup(row)">恢复</el-button></template></el-table-column></el-table></el-card></el-tab-pane>
</el-tabs></main></template>
<style scoped>.system-tabs{margin-top:18px}.settings-form{max-width:650px;margin-top:20px}.card-header{display:flex;justify-content:space-between;align-items:center}</style>
